### ISSUE TITLE
[Enhancement/Feature] Add C# TXD Reading Support rather than using Extern TXDGen

### ISSUE THREAD

**Issue by dreamsyntax** [igorseabra4/HeroesPowerPlant#32]
TXDGen's source code:
https://app.assembla.com/spaces/green-candy/subversion-19/source

* embed into HPP rather than call extern TXDGen.exe
* Alternatively, look into the library MagicTXD  uses (successor to TXDGen)
https://osdn.net/projects/magic-rw/

Low priority, we made TXDGen a silent process now and its much faster since it doesn't need to spawn a window.

**Comment by dreamsyntax** [comment]
Note: MagicTXD author has deleted all of their source code.

**Comment by Sewer56** [comment]
'Can't be arsed' is not a good solution to the problem.

I have informed you many months ago that the latest iteration and a chunk of history of Magic.TXD's source is lost. I have pleaded for you to try to get in touch with the author, in order to ensure that the latest code is not lost forever.

Even if the author was the one who wanted to pull the code of their own accord, it would be a shame if all of the work since 2016/17 or so was permanently lost. I would not want their efforts to be lost in vain.
